### ISSUE TITLE
Visualization of tree

### ISSUE THREAD

**Issue by gb5256** [yiiext/nested-set-behavior#34]
Hello out there. First of all: thanks for this extensions. This is awesome.
I am currently using jstree-nested-behaviour, but that code is a mess.
Yours here look so much better.

I do have one question: What do you guys use to visualize the tree?
Dynatree? Jstree? Something else?
Both have their pros and cons (my fav is dynatree and feed it with a JSON ).
Do you have suggestions?

thanks,
gb5256

**Comment by motin** [comment]
Check out @cornernote's http://cornernote.github.io/yii-menu-module/ for a sample implemetation of a nested set tree visualization
